templateDir: src/main/resources/cstTemplates
files:
  client/model/TimingMonitorData.mustache:
    templateType: SupportingFiles
    destinationFilename: TimingMonitorData.java
    folder: src/gen/java/main/org/openapitools/client/model

  configuration/ConfigurationManager.mustache:
    templateType: SupportingFiles
    destinationFilename: ConfigurationManager.java
    folder: src/gen/java/main/com/group3/monitorClient/configuration

  exception/monitorConfigException.mustache:
    templateType: SupportingFiles
    destinationFilename: MonitorConfigException.java
    folder: src/gen/java/main/com/group3/monitorClient/exception

  messenger/messages/MessageCreator.mustache:
    templateType: SupportingFiles
    destinationFilename: MessageCreator.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages
  
  controller/requirements/AvailableCPURequirement.mustache:
    templateType: SupportingFiles
    destinationFilename: AvailableCPURequirement.java
    folder: src/gen/java/main/com/group3/monitorClient/controller/requirements
  
  messenger/messages/ErrorDataMessage.mustache:
    templateType: SupportingFiles
    destinationFilename: ErrorDataMessage.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages

  messenger/messages/MessageInterface.mustache:
    templateType: SupportingFiles
    destinationFilename: MessageInterface.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages
  
  messenger/messages/MessageTypeID.mustache:
    templateType: SupportingFiles
    destinationFilename: MessageTypeID.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages
  
  messenger/MessengerInterface.mustache:
    templateType: SupportingFiles
    destinationFilename: MessengerInterface.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger

  controller/requirements/Requirement.mustache:
    templateType: SupportingFiles
    destinationFilename: Requirement.java
    folder: src/gen/java/main/com/group3/monitorClient/controller/requirements
  
  messenger/messages/SQLManager.mustache:
    templateType: SupportingFiles
    destinationFilename: SQLManager.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages

  messenger/messages/SQLMessageManager.mustache:
    templateType: SupportingFiles
    destinationFilename: SQLMessageManager.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages

  messenger/messages/TimingMonitorDataMessage.mustache:
    templateType: SupportingFiles
    destinationFilename: TimingMonitorDataMessage.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages

  messenger/Messenger.mustache:
    templateType: SupportingFiles
    destinationFilename: Messenger.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger
  
  client/api/ErrorApi.mustache:
    templateType: SupportingFiles
    destinationFilename: ErrorApi.java
    folder: src/gen/java/main/org/openapitools/client/api
  
  client/model/ErrorData.mustache:
    templateType: SupportingFiles
    destinationFilename: ErrorData.java
    folder: src/gen/java/main/org/openapitools/client/model
  
  client/api/MonitorApi.mustache:
    templateType: SupportingFiles
    destinationFilename: MonitorApi.java
    folder: src/gen/java/main/org/openapitools/client/api

  controller/Controllable.mustache:
    templateType: SupportingFiles
    destinationFilename: Controllable.java
    folder: src/gen/java/main/com/group3/monitorClient/controller

  scheduling/task/AbstractTask.mustache:
    templateType: SupportingFiles
    destinationFilename: AbstractTask.java
    folder: src/gen/java/main/com/group3/monitorClient/scheduling/task

  scheduling/task/CleanUpOldFailedMessagesTask.mustache:
    templateType: SupportingFiles
    destinationFilename: CleanUpOldFailedMessagesTask.java
    folder: src/gen/java/main/com/group3/monitorClient/scheduling/task

  scheduling/NotInitializedException.mustache:
    templateType: SupportingFiles
    destinationFilename: NotInitializedException.java
    folder: src/gen/java/main/com/group3/monitorClient/scheduling

  scheduling/TaskAlreadyExistsException.mustache:
    templateType: SupportingFiles
    destinationFilename: TaskAlreadyExistsException.java
    folder: src/gen/java/main/com/group3/monitorClient/scheduling

  scheduling/TaskDetails.mustache:
    templateType: SupportingFiles
    destinationFilename: TaskDetails.java
    folder: src/gen/java/main/com/group3/monitorClient/scheduling

  scheduling/TaskScheduler.mustache:
    templateType: SupportingFiles
    destinationFilename: TaskScheduler.java
    folder: src/gen/java/main/com/group3/monitorClient/scheduling

  util/MonitorUtils.mustache:
    templateType: SupportingFiles
    destinationFilename: MonitorUtils.java
    folder: src/gen/java/main/com/group3/monitorClient/util

  MonitorClientInterface.mustache:
    templateType: SupportingFiles
    destinationFilename: MonitorClientInterface.java
    folder: src/gen/java/main/com/group3/monitorClient

  api.mustache:
    templateType: API
    destinationFilename: .java

  Controller/apiClient.mustache:
    templateType: API
    destinationFilename: Client.java

  model_test.mustache:
    templateType: ModelTests
    destinationFilename: .java

  test/api_test.mustache:
    templateType: APITests
    destinationFilename: .java