openapi: 3.0.3
info:
  version: "1.0.0"
  title: "Monitor Communication"
  description: "This is a specification for the communication for the monitor system"

paths:
  /monitor:
    post:
      tags:
        - "Monitor"
      summary: "Receive data from the client(s) and server(s)"
      description: "Create a monitor data record"
      operationId: "addMonitorData"
      requestBody:
        content:
          "application/json":
            schema:
              $ref: '#/components/schemas/TimingMonitorData'
      responses:
        "201":
          description: "The request has been fulfilled"
        "404":
          description: "The requested resource could not be found but may be available in the future"
        "500":
          description: "Internal Server Error"

  /error:
    post:
      tags:
        - "Error"
      summary: "Wrap the failing messages in errors"
      description: "Create an error message"
      operationId: "sendError"
      requestBody:
        content:
          "application/json":
            schema:
              $ref: '#/components/schemas/ErrorData'
      responses:
        "200":
          description: "OK"

components:
  schemas:
    ErrorData:
      type: object
      description: "Contain information about errors"
      properties:
        Timestamp:
          type: string
          format: date-time
          description: "The timestamp of when the error occurred"
          example: "1990-12-31T23:59:60Z"
        SenderID:
          type: integer
          format: int64
          description: "The ID of the node on which the error occurred"
          example: 21
        HttpResponse:
          type: integer
          format: int32
          description: "HttpResponse gotten when the error occurred"
          example: 404
        ErrorMessageType:
          type: string
          enum:
            - noConnection
            - HttpError
            - notRecognised
          description: "Error message type for when fx connection is lost"
          example: HttpError
        Comment:
          type: string
          description: "For further elaboration about a given error"
          example: "Trying to contact node 3, error code 404 was received"
      required:
        - Timestamp
        - SenderID
        - ErrorMessageType

    TimingMonitorData:
      type: object
      description: "Contain the required data, that is needed to check timing constraints"
      properties:
        Timestamp:
          type: string
          format: date-time
          description: "The timestamp of the triggering a event"
          example: "1990-12-31T23:59:60Z"
        SenderID:
          type: integer
          format: int64
          description: "The ID of the sender of the monitoring data"
          example: 21
        TargetEndpoint:
          type: string
          description: "The target endpoint of a client side request"
          example: "/example/target/endpoint"
        EventID:
          type: integer
          format: int64
          description: "The unique ID of the event chain"
          example: 57
      required:
        - Timestamp
        - SenderID
        - EventID