jobs:
  include:
    - os: linux
      langauge: java
      jdk: oraclejdk13
      script:
        - mvn -f /home/travis/build/byggemand-bob/Group3-monitoring-distributed-systems/Client clean install
        - mvn -f /home/travis/build/byggemand-bob/Group3-monitoring-distributed-systems/Monitor clean install
        - mvn -f /home/travis/build/byggemand-bob/Group3-monitoring-distributed-systems/Server clean install
      before_install:
        script:
          - ./home/travis/build/byggemand-bob/Group3-monitoring-distributed-systems/Server/testScript.sh