language: java
os: linux
dist: "xenial"
jobs:
  include:
    - os: linux
      python: "3.7"
      jdk: oraclejdk11
      script:
        - python /home/travis/build/byggemand-bob/Group3-monitoring-distributed-systems/RenameTemplatePathInConfig.py
        - mvn -f /home/travis/build/byggemand-bob/Group3-monitoring-distributed-systems/Client clean install
        - mvn -f /home/travis/build/byggemand-bob/Group3-monitoring-distributed-systems/Monitor clean install
        - mvn -f /home/travis/build/byggemand-bob/Group3-monitoring-distributed-systems/Server clean install
        - mvn -f /home/travis/build/byggemand-bob/Group3-monitoring-distributed-systems/Monitor-Client clean install