templateDir: src/main/resources/cstTemplates
files:
  MonitorClientInterface.mustache:
    templateType: SupportingFiles
    destinationFilename: MonitorClientInterface.java
    folder: src/gen/java/main/com/group3/monitor/client

  client/ApiCallback.mustache:
    templateType: SupportingFiles
    destinationFilename: ApiCallback.java
    folder: src/gen/java/main/org/openapitools/client

  client/ApiClient.mustache:
    templateType: SupportingFiles
    destinationFilename: ApiClient.java
    folder: src/gen/java/main/org/openapitools/client

  client/ApiException.mustache:
    templateType: SupportingFiles
    destinationFilename: ApiException.java
    folder: src/gen/java/main/org/openapitools/client

  client/ApiResponse.mustache:
    templateType: SupportingFiles
    destinationFilename: ApiResponse.java
    folder: src/gen/java/main/org/openapitools/client

  client/Configuration.mustache:
    templateType: SupportingFiles
    destinationFilename: Configuration.java
    folder: src/gen/java/main/org/openapitools/client

  client/GzipRequestInterceptor.mustache:
    templateType: SupportingFiles
    destinationFilename: GzipRequestInterceptor.java
    folder: src/gen/java/main/org/openapitools/client

  client/JSON.mustache:
    templateType: SupportingFiles
    destinationFilename: JSON.java
    folder: src/gen/java/main/org/openapitools/client

  client/Pair.mustache:
    templateType: SupportingFiles
    destinationFilename: Pair.java
    folder: src/gen/java/main/org/openapitools/client

  client/ProgressRequestBody.mustache:
    templateType: SupportingFiles
    destinationFilename: ProgressRequestBody.java
    folder: src/gen/java/main/org/openapitools/client

  client/ProgressResponseBody.mustache:
    templateType: SupportingFiles
    destinationFilename: ProgressResponseBody.java
    folder: src/gen/java/main/org/openapitools/client

  client/ServerConfiguration.mustache:
    templateType: SupportingFiles
    destinationFilename: ServerConfiguration.java
    folder: src/gen/java/main/org/openapitools/client

  client/ServerVariable.mustache:
    templateType: SupportingFiles
    destinationFilename: ServerVariable.java
    folder: src/gen/java/main/org/openapitools/client

  client/StringUtil.mustache:
    templateType: SupportingFiles
    destinationFilename: StringUtil.java
    folder: src/gen/java/main/org/openapitools/client

  api/MonitorApi.mustache:
    templateType: SupportingFiles
    destinationFilename: MonitorApi.java
    folder: src/gen/java/main/com/group3/monitor/api

  auth/ApiKeyAuth.mustache:
    templateType: SupportingFiles
    destinationFilename: ApiKeyAuth.java
    folder: src/gen/java/main/org/openapitools/client/auth

  auth/Authentication.mustache:
    templateType: SupportingFiles
    destinationFilename: Authentication.java
    folder: src/gen/java/main/org/openapitools/client/auth

  auth/HttpBasicAuth.mustache:
    templateType: SupportingFiles
    destinationFilename: HttpBasicAuth.java
    folder: src/gen/java/main/org/openapitools/client/auth

  auth/HttpBearerAuth.mustache:
    templateType: SupportingFiles
    destinationFilename: HttpBearerAuth.java
    folder: src/gen/java/main/org/openapitools/client/auth

  model/timingMonitorData.mustache:
    templateType: SupportingFiles
    destinationFilename: TimingMonitorData.java
    folder: src/gen/java/main/com/group3/monitor/model

  api/controller/apiController.mustache:
    templateType: API
    destinationFilename: Controller.java
  
  api/api.mustache:
    templateType: API
    destinationFilename: .java

  configuration/configManager.mustache:
    templateType: SupportingFiles
    destinationFilename: ConfigurationManager.java
    folder: src/gen/java/main/com/group3/monitor/configuration
  
  exception/monitorConfigException.mustache:
    templateType: SupportingFiles
    destinationFilename: MonitorConfigException.java
    folder: src/gen/java/main/com/group3/monitor/exception

  controller/MonitorClientInterface.mustache:
    templateType: SupportingFiles
    destinationFilename: MonitorClientInterface.java
    folder: src/gen/java/main/com/group3/monitorClient/controller
  
  messenger/messages/MessageCreator.mustache:
    templateType: SupportingFiles
    destinationFilename: MessageCreator.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages
  
  messenger/lazyMessenger/requirements/AvailableCPURequirement.mustache:
    templateType: SupportingFiles
    destinationFilename: AvailableCPURequirement.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/lazyMessenger/requirements
  
  messenger/messages/ErrorDataMessage.mustache:
    templateType: SupportingFiles
    destinationFilename: ErrorDataMessage.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages
  
  messenger/GreedyMessenger.mustache:
    templateType: SupportingFiles
    destinationFilename: GreedyMessenger.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger
  
  messenger/lazyMessenger/LazyMessenger.mustache:
    templateType: SupportingFiles
    destinationFilename: LazyMessenger.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/lazyMessenger
  
  messenger/messages/MessageInterface.mustache:
    templateType: SupportingFiles
    destinationFilename: MessageInterface.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages
  
  messenger/messages/MessageTypeID.mustache:
    templateType: SupportingFiles
    destinationFilename: MessageTypeID.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages
  
  messenger/MessengerInterface.mustache:
    templateType: SupportingFiles
    destinationFilename: MessengerInterface.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger
  
  messenger/queue/PersistentSQLQueue.mustache:
    templateType: SupportingFiles
    destinationFilename: PersistentSQLQueue.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/queue
  
  messenger/queue/QueueInterface.mustache:
    templateType: SupportingFiles
    destinationFilename: QueueInterface.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/queue
  
  messenger/lazyMessenger/requirements/Requirement.mustache:
    templateType: SupportingFiles
    destinationFilename: Requirement.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/lazyMessenger/requirements
  
  messenger/queue/SecureSynchronizedQueue.mustache:
    templateType: SupportingFiles
    destinationFilename: SecureSynchronizedQueue.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/queue
  
  messenger/messages/SQLManager.mustache:
    templateType: SupportingFiles
    destinationFilename: SQLManager.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages
  
  messenger/queue/SynchronizedQueue.mustache:
    templateType: SupportingFiles
    destinationFilename: SynchronizedQueue.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/queue
  
  messenger/messages/TimingMonitorDataMessage.mustache:
    templateType: SupportingFiles
    destinationFilename: TimingMonitorDataMessage.java
    folder: src/gen/java/main/com/group3/monitorClient/messenger/messages
  
  client/api/ErrorApi.mustache:
    templateType: SupportingFiles
    destinationFilename: ErrorApi.java
    folder: src/gen/java/main/org/openapitools/client/api
  
  client/model/ErrorData.mustache:
    templateType: SupportingFiles
    destinationFilename: ErrorData.java
    folder: src/gen/java/main/org/openapitools/client/model
  
  client/api/MonitorApi.mustache:
    templateType: SupportingFiles
    destinationFilename: MonitorApi.java
    folder: src/gen/java/main/org/openapitools/client/api
  
  client/model/TimingMonitorData.mustache:
    templateType: SupportingFiles
    destinationFilename: TimingMonitorData.java
    folder: src/gen/java/main/org/openapitools/client/model