templateDir: C:/Repositories/P6/Server/src/main/resources/cstTemplates
files:
  MonitorClientInterface.mustache:
    templateType: SupportingFiles
    destinationFilename: MonitorClientInterface.java
    folder: src/gen/java/main/com/Group3/monitorClient/controller